### PR TITLE
Upgrade Shiro to 1.2.6

### PR DESCRIPTION
**Pull request by jochenberger**

### CODE REVIEW

**Comment by jochenberger** [comment]
Do you intend to create a release anytime soon?

**Comment by kaosko** [comment]
No, there's nothing relevant in 1.2.6, users can easily specify that version if they need

**Comment by jochenberger** [comment]
1.2.5 will cause issues for users of Gradle 2.14 (https://issues.apache.org/jira/browse/SHIRO-567).

**Comment by kaosko** [comment]
Yes, I'm fully aware of that as a Shiro committer. They can use a previous release for the time being.

**Pull request merged**
